name: Issue
description: "File a report for a bug/issue inside of Nazi Zombies: Portable"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help us improve KatOS! Please note that these tickets are to be treated seriously, any content deemed disrespectful, non-serious, or does not adequately follow the steps below will be immediately closed and potentially removed.

        This is an English-only form. If you do not speak English, please use Google Translate or similar to translate into English.
  - type: textarea
    attributes:
      label: Description
      description: "Provide a description of the feature you are requesting."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Verification of Submission
      description: Verify that you have selected options above and filled out request properly and in full. 
      options:
        - label: I agree that I properly filled out the items listed above. I understand an issue may be closed if process is not properly followed.
          required: true