title    Try or Install KatOS (%ARCH%, UEFI) with speech
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% accessibility=on quiet splash loglevel=3 systemd.show_status=false rd.udev.log_level=3 rd.systemd.show_status=false vt.global_cursor_default=0
